
spring: 
 datasource:
    type: org.apache.tomcat.dbcp.dbcp2.BasicDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: manager