/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TxMgmtProj9.DTx.Atomikos;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
